### ISSUE TITLE
variational bayes prune

### ISSUE THREAD

**Issue by fredRos** [fredRos/pypmc#46]
The variational Bayes `run` method crashed with an uninformative prior if the prune value is larger than the total number of data points, or in any case larger than what any component is assigned. We should catch this case and output a useful message.

Here is the error

```
After update 1: bound=14732.586708919, K=3, N_k=[  51.84580251  135.41111975    4.74307774]
Traceback (most recent call last):
  File "../py-eos/vb.py", line 217, in <module>
    vb.run()
  File "../py-eos/vb.py", line 143, in run
    self.vb.run(**kwargs)
  File "pypmc/mix_adapt/variational.pyx", line 356, in pypmc.mix_adapt.variational.GaussianInference.run
 (pypmc/mix_adapt/variational.c:6439)
  File "pypmc/mix_adapt/variational.pyx", line 279, in pypmc.mix_adapt.variational.GaussianInference.pru
ne (pypmc/mix_adapt/variational.c:5756)
  File "pypmc/mix_adapt/variational.pyx", line 119, in pypmc.mix_adapt.variational.GaussianInference.E_s
tep (pypmc/mix_adapt/variational.c:3412)
  File "pypmc/mix_adapt/variational.pyx", line 783, in pypmc.mix_adapt.variational.GaussianInference._up
date_expectation_gauss_exponent (pypmc/mix_adapt/variational.c:13437)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

and the offending line is https://github.com/fredRos/pypmc/blob/master/pypmc/mix_adapt/variational.pyx#L783
```
double  [:,:] W = _np.empty_like(self.W[0])
```
because `W` has been emptied

**Comment by fredRos** [comment]
A minimal example reproducing the error

```python
import numpy as np
import pypmc
vb = pypmc.mix_adapt.variational.GaussianInference(np.random.randn(500, 2))
vb.run(prune=600)
```
