### ISSUE TITLE
host doc on readthedocs

### ISSUE THREAD

**Issue by fredRos** [fredRos/pypmc#51]
I tried to recreate the steps taken by the readthedocs builder. It doesn't work for them but works on my machine. Something with the environment but what? After installing pypmc successfully, I guess they change to the `doc` subdirectory of a checkout, then they run 

```
python /home/docs/checkouts/readthedocs.org/user_builds/pypmc/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html

Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/envs/latest/local/lib/python3.4/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opt-b readthedocss.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/envs/latest/local/lib/python3.4/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/envs/latest/local/lib/python3.4/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/envs/latest/local/lib/python3.4/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "conf.py", line 48, in <module>
    from pypmc import __version__ as pypmc_versionpython /home/docs/checkouts/readthedocs.org/user_builds/pypmc/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html

Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/envs/latest/local/lib/python3.4/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/envs/latest/local/lib/python3.4/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/envs/latest/local/lib/python3.4/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/envs/latest/local/lib/python3.4/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "conf.py", line 48, in <module>
    from pypmc import __version__ as pypmc_version
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/__init__.py", line 9, in <module>
    from . import mix_adapt, density, sampler, tools
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/mix_adapt/__init__.py", line 7, in <module>
    from . import hierarchical, variational, pmc, r_value
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/mix_adapt/r_value.py", line 7, in <module>
    from ..tools._doc import _add_to_docstring
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/tools/__init__.py", line 6, in <module>
    from ._partition import partition, patch_data
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/tools/_partition.py", line 6, in <module>
    from ..density.gauss import Gauss
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/density/__init__.py", line 6, in <module>
    from . import gauss, student_t, mixture, base
ImportError: cannot import name 'gauss'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/density/__init__.py", line 6, in <module>
    from . import gauss, student_t, mixture, base
ImportError: cannot import name 'gauss'
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/__init__.py", line 9, in <module>
    from . import mix_adapt, density, sampler, tools
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/mix_adapt/__init__.py", line 7, in <module>
    from . import hierarchical, variational, pmc, r_value
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/mix_adapt/r_value.py", line 7, in <module>
    from ..tools._doc import _add_to_docstring
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/tools/__init__.py", line 6, in <module>
    from ._partition import partition, patch_data
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/tools/_partition.py", line 6, in <module>
    from ..density.gauss import Gauss
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/density/__init__.py", line 6, in <module>
    from . import gauss, student_t, mixture, base
ImportError: cannot import name 'gauss'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/pypmc/checkouts/latest/pypmc/density/__init__.py", line 6, in <module>
    from . import gauss, student_t, mixture, base
ImportError: cannot import name 'gauss'
```

when I run the same command on my installation

```
$ python /usr/bin/sphinx-build  -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.2.2
loading translations [en]... done

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 139, in __init__
    self._init_builder(buildername)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 192, in _init_builder
    raise SphinxError('Builder name %s not registered' % buildername)
SphinxError: Builder name readthedocs not registered
```

 without the builder argument `-b readthedocs`, I get

```
~/workspace/pypmc/doc (master)$ python /usr/bin/sphinx-build  -T -E  -d _build/doctrees-readthedocs -D language=en . _build/htmlRunning Sphinx v1.2.2
loading translations [en]... done
No builder selected, using default: html
building [html]: targets for 10 source files that are out of date
updating environment: 10 added, 0 changed, 0 removed
reading sources... [100%] user_guide                                                                                                
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... do$ python /usr/bin/sphinx-build  -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.2.2
loading translations [en]... done

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 139, in __init__
    self._init_builder(buildername)
  File "/usr/lib/python2.7/dist-packages/sphinx/application.py", line 192, in _init_builder
    raise SphinxError('Builder name %s not registered' % buildername)
SphinxError: Builder name readthedocs not registered
ne
writing output... [100%] user_guide                                                                                                 
writing additional files... (14 module code pages) _modules/index genindex py-modindex search
copying images... [100%] _build/examples/uniting_markov_chains_and_variational_bayes.png                                            
copying static files... done
copying extra files... done
dumping search index... done
dumping object inventory... done
build succeeded.
```

From any other directory than `doc/`, I get

```
~/workspace/pypmc (master)$ python /usr/bin/sphinx-build  -T -E  -d _build/doctrees-readthedocs -D language=en . _build/html
Error: Source directory doesn't contain a conf.py file.
```

so the error might have to do with the builder or just the way the installation is different on their system.

**Comment by fredRos** [comment]
The answer is that readthe docs doesn't work with plot directive, which is used to run the examples and capture their output. Since this is useful, I can't use readthedocs and have to host the files myself.
http://stackoverflow.com/questions/27228115/is-it-possible-to-upload-sphinx-pre-generated-html-documents-into-readthedocs-si
