### ISSUE TITLE
Installing cython as a dependency

### ISSUE THREAD

**Issue by fredRos** [fredRos/pypmc#63]
There seems to be an error if cython isn't installed yet, then it's supposedly installed but not available immediately. The second try works but it's not clear if it works in the 1st or not
```
 pip install .                            22:23:18  ☁  cython-language-level ☂ ⚡ ✭
Processing /home/beaujefr/workspace/pypmc
Collecting cython>=0.21 (from pypmc==1.1.1)
  Using cached https://files.pythonhosted.org/packages/b8/c0/500afce93187b9d94d5c6e80a3032f90bf559bd4
c8d12b45a10bc9a67b92/Cython-0.29.10-cp37-cp37m-manylinux1_x86_64.whl                                
Requirement already satisfied: numpy<2.0,>=1.6 in /home/beaujefr/.local/miniconda2/envs/pypmc3.7/lib/
python3.7/site-packages (from pypmc==1.1.1) (1.16.4)                                                
Requirement already satisfied: scipy in /home/beaujefr/.local/miniconda2/envs/pypmc3.7/lib/python3.7/
site-packages (from pypmc==1.1.1) (1.3.0)                                                           
Building wheels for collected packages: pypmc
  Building wheel for pypmc (setup.py) ... error
  ERROR: Complete output from command /home/beaujefr/.local/miniconda2/envs/pypmc3.7/bin/python -u -c
 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-n0pt9b77/setup.py'"'"';f=getattr(token
ize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();ex
ec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-3f82nre5 --python-tag cp37
:                                                                                                   
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-n0pt9b77/setup.py", line 94, in <module>
      setup_package()
    File "/tmp/pip-req-build-n0pt9b77/setup.py", line 88, in setup_package
      setup_args['ext_modules'] = get_extensions()
    File "/tmp/pip-req-build-n0pt9b77/setup.py", line 28, in get_extensions
      from Cython.Build import cythonize
  ModuleNotFoundError: No module named 'Cython'
  ----------------------------------------
  ERROR: Failed building wheel for pypmc
  Running setup.py clean for pypmc
Failed to build pypmc
Installing collected packages: cython, pypmc
  Found existing installation: pypmc 1.1.1
    Uninstalling pypmc-1.1.1:
      Successfully uninstalled pypmc-1.1.1
  Running setup.py install for pypmc ... done
Successfully installed cython-0.29.10 pypmc-1.1.1
```

**Comment by fredRos** [comment]
Seems it works, the unit tests pass

```
 cd                                       22:33:16  ☁  cython-language-level ☂ ⚡ ✭
(pypmc3.7) [~] nosetests pypmc                                                             22:33:31 
.....................................................................................................
........................S...S..                                                                     
----------------------------------------------------------------------
Ran 130 tests in 13.200s

OK (SKIP=2)
```

**Comment by fredRos** [comment]
I guess it just fails to build the wheel but installs fine nonetheless. Since I don't care much for the wheel atm, all seems ok
